# Generated by Django 5.2.4 on 2025-07-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.IntegerField()),
                ('Humidity', models.IntegerField()),
                ('Precipitation', models.IntegerField()),
                ('Wind', models.IntegerField()),
            ],
        ),
    ]
